# Generated by Django 4.2.20 on 2025-07-04 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('form_type', models.CharField(choices=[('general', 'General Research Consent'), ('eeg', 'EEG Recording Consent'), ('audio', 'Audio Recording Consent'), ('data_sharing', 'Data Sharing Consent'), ('custom', 'Custom Consent Form')], default='general', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('content', models.TextField(help_text='HTML content of the consent form')),
                ('summary', models.TextField(blank=True, help_text='Brief summary of what this consent covers')),
                ('is_active', models.BooleanField(default=True)),
                ('expiration_period', models.IntegerField(default=365, help_text='Days until consent expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_consent_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('title', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ResearcherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('research_interests', models.TextField(blank=True)),
                ('office_phone', models.CharField(blank=True, max_length=20)),
                ('office_location', models.CharField(blank=True, max_length=100)),
                ('can_create_studies', models.BooleanField(default=True)),
                ('can_manage_participants', models.BooleanField(default=True)),
                ('can_export_data', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='researcher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Prefer not to say')], max_length=1, null=True)),
                ('handedness', models.CharField(blank=True, choices=[('R', 'Right-handed'), ('L', 'Left-handed'), ('A', 'Ambidextrous')], max_length=1, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('native_language', models.CharField(blank=True, max_length=50)),
                ('has_neurological_conditions', models.BooleanField(default=False)),
                ('neurological_notes', models.TextField(blank=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('has_valid_consent', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('signature_data', models.TextField(blank=True, help_text='Base64 encoded signature image')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('agreed_to_data_sharing', models.BooleanField(default=False)),
                ('agreed_to_future_research', models.BooleanField(default=False)),
                ('agreed_to_audio_recording', models.BooleanField(default=False)),
                ('agreed_to_eeg_recording', models.BooleanField(default=False)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('renewal_notification_sent', models.BooleanField(default=False)),
                ('renewal_notification_date', models.DateTimeField(blank=True, null=True)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('withdrawal_date', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='user_management.consentform')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='user_management.participantprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('participant', 'consent_form')},
            },
        ),
    ]
