# Generated by Django 4.2.20 on 2025-07-04 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='available_weekdays',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='available_weekends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='is_open_to_invitations',
            field=models.BooleanField(default=False, help_text='Allow researchers to send participation invitations'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='max_sessions_per_month',
            field=models.IntegerField(default=4, help_text='Maximum research sessions per month'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='preferred_session_duration',
            field=models.IntegerField(default=60, help_text='Preferred session duration in minutes'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='preferred_time_afternoon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='preferred_time_evening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='preferred_time_morning',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ResearchParticipationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('open_invitation', 'Open to All Researchers'), ('specific_researcher', 'Specific Researcher Request')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Researcher Review'), ('approved', 'Approved by Researcher'), ('confirmed', 'Confirmed by Participant'), ('declined', 'Declined'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('participant_message', models.TextField(blank=True, help_text='Message from participant to researcher')),
                ('researcher_response', models.TextField(blank=True, help_text='Response from researcher')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('preferred_session_count', models.IntegerField(default=1)),
                ('preferred_duration', models.IntegerField(default=60, help_text='Duration in minutes')),
                ('availability_notes', models.TextField(blank=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_requests', to='user_management.participantprofile')),
                ('researcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='user_management.researcherprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('estimated_duration', models.IntegerField(help_text='Duration in minutes')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('equipment_notes', models.TextField(blank=True)),
                ('data_collected', models.BooleanField(default=False)),
                ('data_quality_rating', models.IntegerField(blank=True, help_text='Quality rating 1-5', null=True)),
                ('session_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='user_management.participantprofile')),
                ('participation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.researchparticipationrequest')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_sessions', to='user_management.researcherprofile')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_currently_available', models.BooleanField(default=True)),
                ('availability_start_date', models.DateField(blank=True, null=True)),
                ('availability_end_date', models.DateField(blank=True, null=True)),
                ('monday_available', models.BooleanField(default=True)),
                ('tuesday_available', models.BooleanField(default=True)),
                ('wednesday_available', models.BooleanField(default=True)),
                ('thursday_available', models.BooleanField(default=True)),
                ('friday_available', models.BooleanField(default=True)),
                ('saturday_available', models.BooleanField(default=False)),
                ('sunday_available', models.BooleanField(default=False)),
                ('earliest_time', models.TimeField(default='09:00')),
                ('latest_time', models.TimeField(default='17:00')),
                ('max_sessions_per_week', models.IntegerField(default=2)),
                ('min_break_between_sessions', models.IntegerField(default=24, help_text='Minimum hours between sessions')),
                ('special_requirements', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='user_management.participantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_data', models.TextField(help_text='Base64 encoded signature image')),
                ('signature_hash', models.CharField(help_text='SHA-256 hash of signature', max_length=64)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signing_duration', models.FloatField(blank=True, help_text='Time taken to sign in seconds', null=True)),
                ('signature_points', models.IntegerField(blank=True, help_text='Number of points in signature path', null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_method', models.CharField(blank=True, max_length=50)),
                ('verification_timestamp', models.DateTimeField(blank=True, null=True)),
                ('encryption_key_id', models.CharField(blank=True, max_length=100)),
                ('consent_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_signature', to='user_management.consentrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('form_created', 'Consent Form Created'), ('form_updated', 'Consent Form Updated'), ('form_assigned', 'Form Assigned to Participant'), ('form_viewed', 'Form Viewed by Participant'), ('consent_signed', 'Consent Signed'), ('consent_declined', 'Consent Declined'), ('consent_withdrawn', 'Consent Withdrawn'), ('consent_expired', 'Consent Expired'), ('reminder_sent', 'Reminder Sent'), ('signature_verified', 'Signature Verified'), ('data_accessed', 'Participant Data Accessed'), ('export_performed', 'Data Export Performed')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data in JSON format')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Mark as sensitive for compliance reporting')),
                ('compliance_category', models.CharField(blank=True, help_text='Category for compliance reporting (GDPR, HIPAA, etc.)', max_length=50)),
                ('consent_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='user_management.consentform')),
                ('consent_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='user_management.consentrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='user_manage_user_id_22bd0a_idx'), models.Index(fields=['action', 'timestamp'], name='user_manage_action_67c30e_idx'), models.Index(fields=['consent_record', 'timestamp'], name='user_manage_consent_d80e6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('sent', 'Sent to Participant'), ('viewed', 'Viewed by Participant'), ('signed', 'Signed'), ('declined', 'Declined'), ('expired', 'Expired')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('assignment_message', models.TextField(blank=True, help_text='Message from researcher to participant')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('is_urgent', models.BooleanField(default=False)),
                ('priority_level', models.IntegerField(default=1, help_text='1=Low, 2=Medium, 3=High')),
                ('consent_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='user_management.consentform')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_assignments', to='user_management.participantprofile')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_assignments', to='user_management.researcherprofile')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('participant', 'consent_form', 'researcher')},
            },
        ),
    ]
