# Generated by Django 5.1.6 on 2025-07-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_participantprofile_available_weekdays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchparticipationrequest',
            name='compensation',
            field=models.CharField(blank=True, help_text='Compensation offered to participants', max_length=100),
        ),
        migrations.AddField(
            model_name='researchparticipationrequest',
            name='session_duration',
            field=models.CharField(blank=True, help_text='Expected session duration', max_length=50),
        ),
        migrations.AddField(
            model_name='researchparticipationrequest',
            name='study_description',
            field=models.TextField(blank=True, help_text='Detailed description of the study'),
        ),
        migrations.AddField(
            model_name='researchparticipationrequest',
            name='study_title',
            field=models.CharField(blank=True, help_text='Title of the research study', max_length=200),
        ),
    ]
