# Generated by Django 5.1.6 on 2025-07-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_researchparticipationrequest_compensation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchparticipationrequest',
            name='contact_method',
            field=models.CharField(blank=True, default='email', help_text='Preferred contact method', max_length=20),
        ),
    ]
