# Generated by Django 4.2.20 on 2025-03-29 15:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransformerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('dataset_path', models.CharField(max_length=255)),
                ('model_path', models.CharField(max_length=255)),
                ('accuracy', models.FloatField(default=0.0)),
                ('loss', models.FloatField(default=0.0)),
                ('conv_filters', models.IntegerField(default=32)),
                ('conv_kernel_size', models.IntegerField(default=3)),
                ('transformer_heads', models.IntegerField(default=4)),
                ('transformer_dim', models.IntegerField(default=64)),
                ('transformer_layers', models.IntegerField(default=2)),
                ('dropout_rate', models.FloatField(default=0.2)),
                ('epochs', models.IntegerField(default=50)),
                ('batch_size', models.IntegerField(default=32)),
                ('learning_rate', models.FloatField(default=0.001)),
                ('validation_split', models.FloatField(default=0.2)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('word_list', models.TextField(blank=True, help_text='Comma-separated list of words to include')),
                ('apply_filtering', models.BooleanField(default=True, help_text='Whether to apply bandpass filtering during preprocessing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransformerPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicted_word', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('actual_word', models.CharField(blank=True, max_length=100, null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('participant', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='eeg_transformer.transformermodel')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('dataset_path', models.CharField(max_length=255)),
                ('word_list', models.TextField(blank=True, help_text='Comma-separated list of words to include')),
                ('conv_filters', models.IntegerField(default=32)),
                ('conv_kernel_size', models.IntegerField(default=3)),
                ('transformer_heads', models.IntegerField(default=4)),
                ('transformer_dim', models.IntegerField(default=64)),
                ('transformer_layers', models.IntegerField(default=2)),
                ('dropout_rate', models.FloatField(default=0.2)),
                ('epochs', models.IntegerField(default=50)),
                ('batch_size', models.IntegerField(default=32)),
                ('learning_rate', models.FloatField(default=0.001)),
                ('validation_split', models.FloatField(default=0.2)),
                ('apply_filtering', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.CharField(default='anonymous', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resulting_model', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_job', to='eeg_transformer.transformermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_path', models.CharField(max_length=255)),
                ('accuracy', models.FloatField(default=0.0)),
                ('eval_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='eeg_transformer.transformermodel')),
            ],
        ),
    ]
