# Generated by Django 5.1.6 on 2025-02-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('stage', models.CharField(choices=[('stage1', 'Stage 1'), ('stage2', 'Stage 2'), ('stage3', 'Stage 3'), ('stage4', 'Stage 4'), ('stage5', 'Stage 5')], default='stage1', max_length=10)),
                ('slug', models.SlugField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
