# Generated by Django 4.2.20 on 2025-07-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0003_unified_session_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualtrialsession',
            name='rest_duration',
            field=models.IntegerField(default=2000, help_text='Duration of rest periods in milliseconds (0 = no rest)'),
        ),
    ]
