# Generated by Django 5.2.1 on 2025-06-27 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotorImagerySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=100)),
                ('session_name', models.CharField(help_text='Descriptive name for this session', max_length=200)),
                ('imagery_duration', models.IntegerField(default=4000, help_text='Duration of motor imagery in milliseconds')),
                ('cue_duration', models.IntegerField(default=2000, help_text='Duration of cue display in milliseconds')),
                ('rest_duration', models.IntegerField(default=2000, help_text='Duration between trials in milliseconds')),
                ('trials_per_class', models.IntegerField(default=20, help_text='Number of trials per imagery class')),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('eeg_data_file', models.CharField(blank=True, help_text='Path to generated EEG CSV file', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MotorImageryTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_number', models.IntegerField()),
                ('imagery_class', models.CharField(choices=[('LEFT_HAND', 'Left Hand Clenching'), ('RIGHT_HAND', 'Right Hand Clenching'), ('FEET', 'Both Feet Movement'), ('REST', 'Rest Period')], max_length=20)),
                ('cue_start_time', models.DateTimeField()),
                ('imagery_start_time', models.DateTimeField()),
                ('trial_end_time', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='motor_imagery.motorimagerysession')),
            ],
            options={
                'ordering': ['trial_number'],
                'unique_together': {('session', 'trial_number')},
            },
        ),
    ]
