# Generated by Django 5.2.1 on 2025-07-09 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bci', '0002_update_approach_choices'),
        ('bci_communicator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationevent',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Moving Window Communication Event', 'verbose_name_plural': 'Moving Window Communication Events'},
        ),
        migrations.AlterModelOptions(
            name='communicationsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Moving Window Communication Session', 'verbose_name_plural': 'Moving Window Communication Sessions'},
        ),
        migrations.AddField(
            model_name='communicationevent',
            name='window_data',
            field=models.JSONField(blank=True, default=dict, help_text='Window position and movement data'),
        ),
        migrations.AddField(
            model_name='communicationsession',
            name='window_positions',
            field=models.JSONField(blank=True, default=dict, help_text='Additional window position data'),
        ),
        migrations.AlterField(
            model_name='communicationevent',
            name='event_type',
            field=models.CharField(choices=[('MOTOR_PREDICTION', 'Motor Imagery Prediction'), ('P300_CONFIRMATION', 'P300 Confirmation'), ('LETTER_SELECTED', 'Letter Selected'), ('WORD_COMPLETED', 'Word Auto-Completed'), ('SPACE_INSERTED', 'Space Inserted'), ('STATE_CHANGED', 'State Changed'), ('WINDOW_MOVED', 'Window Moved'), ('COOLDOWN_STARTED', 'Cooldown Started'), ('COOLDOWN_ENDED', 'Cooldown Ended'), ('WINDOW_RESET', 'Windows Reset'), ('GROUP_SWITCHED', 'Active Group Switched')], max_length=30),
        ),
        migrations.AlterField(
            model_name='communicationevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='communicationevent',
            name='probabilities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='communicationevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bci_communicator.communicationsession'),
        ),
        migrations.AlterField(
            model_name='communicationsession',
            name='communication_state',
            field=models.CharField(choices=[('NAVIGATING', 'Window Navigation'), ('SELECTING', 'Letter Selection'), ('CONFIRMING', 'P300 Word Confirmation')], default='NAVIGATING', max_length=20),
        ),
        migrations.AlterField(
            model_name='communicationsession',
            name='current_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='communicationsession',
            name='current_word',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='communicationsession',
            name='left_side_letters',
            field=models.JSONField(default=list, help_text='Letters controlled by left hand motor imagery'),
        ),
        migrations.AlterField(
            model_name='communicationsession',
            name='motor_imagery_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mi_communication_sessions', to='bci.trainedmodel'),
        ),
        migrations.AlterField(
            model_name='communicationsession',
            name='p300_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p300_communication_sessions', to='bci.trainedmodel'),
        ),
        migrations.AlterField(
            model_name='communicationsession',
            name='right_side_letters',
            field=models.JSONField(default=list, help_text='Letters controlled by right hand motor imagery'),
        ),
        migrations.AlterField(
            model_name='communicationsession',
            name='selected_side',
            field=models.CharField(blank=True, choices=[('LEFT', 'Left Group Active'), ('RIGHT', 'Right Group Active')], help_text='Which letter group is currently active', max_length=10),
        ),
        migrations.AlterField(
            model_name='communicationsession',
            name='selection_index',
            field=models.IntegerField(default=0, help_text='Current left window position (0-5)'),
        ),
        migrations.AlterField(
            model_name='communicationsession',
            name='session_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='communicationsession',
            name='vocabulary_words',
            field=models.JSONField(default=list, help_text='Vocabulary for P300 word suggestions'),
        ),
        migrations.AddIndex(
            model_name='communicationevent',
            index=models.Index(fields=['session', 'event_type', '-timestamp'], name='bci_communi_session_1a8eaa_idx'),
        ),
    ]
