# Generated by Django 5.2.1 on 2025-07-08 23:14

import bci_communicator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bci_communicator', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communicationevent',
            new_name='bci_communi_session_d24b72_idx',
            old_name='bci_communi_session_b8c442_idx',
        ),
        migrations.RenameIndex(
            model_name='communicationevent',
            new_name='bci_communi_event_t_4f4cfa_idx',
            old_name='bci_communi_event_t_4f8e9a_idx',
        ),
        migrations.AlterField(
            model_name='communicationsession',
            name='left_side_letters',
            field=models.JSONField(default=bci_communicator.models.get_default_left_letters),
        ),
        migrations.AlterField(
            model_name='communicationsession',
            name='right_side_letters',
            field=models.JSONField(default=bci_communicator.models.get_default_right_letters),
        ),
        migrations.AlterField(
            model_name='communicationsession',
            name='vocabulary_words',
            field=models.JSONField(default=bci_communicator.models.get_default_vocabulary),
        ),
    ]
