# Generated by Django 4.2.20 on 2025-04-20 16:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EEGModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('dataset_path', models.CharField(max_length=255)),
                ('model_path', models.CharField(max_length=255)),
                ('accuracy', models.FloatField(default=0.0)),
                ('loss', models.FloatField(default=0.0)),
                ('speech_accuracy', models.FloatField(default=0.0, help_text='Accuracy of speech detection model')),
                ('word_accuracy', models.FloatField(default=0.0, help_text='Accuracy of word classification model')),
                ('model_type', models.CharField(choices=[('tensorflow', 'TensorFlow RNN'), ('pytorch', 'PyTorch CNN-LSTM')], default='pytorch', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('dataset_path', models.CharField(max_length=255)),
                ('word_list', models.TextField(blank=True, help_text='Comma-separated list of words to include')),
                ('apply_filtering', models.BooleanField(default=True, help_text='Whether to apply bandpass filtering during preprocessing')),
                ('use_mne', models.BooleanField(default=True, help_text='Whether to use advanced MNE preprocessing')),
                ('epochs', models.IntegerField(default=50)),
                ('batch_size', models.IntegerField(default=32)),
                ('learning_rate', models.FloatField(default=0.001)),
                ('validation_split', models.FloatField(default=0.2)),
                ('hidden_units', models.IntegerField(default=64)),
                ('dropout_rate', models.FloatField(default=0.2)),
                ('recurrent_dropout', models.FloatField(default=0.2)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True)),
                ('model_type', models.CharField(choices=[('tensorflow', 'TensorFlow RNN'), ('pytorch', 'PyTorch CNN-LSTM')], default='pytorch', max_length=20)),
                ('user', models.CharField(default='anonymous', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_data_path', models.CharField(blank=True, max_length=255)),
                ('predicted_word', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('is_speech', models.BooleanField(help_text='Whether the input was classified as speech', null=True)),
                ('speech_confidence', models.FloatField(default=0.0, help_text='Confidence of speech detection')),
                ('actual_word', models.CharField(blank=True, max_length=100, null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('participant', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='pi_main.eegmodel')),
            ],
        ),
        migrations.AddField(
            model_name='eegmodel',
            name='training_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_model', to='pi_main.trainingjob'),
        ),
    ]
