# Generated by Django 4.2.20 on 2025-03-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='apply_filtering',
            field=models.BooleanField(default=False, help_text='Whether to apply bandpass filtering during preprocessing'),
        ),
    ]
