# Generated by Django 4.2.20 on 2025-04-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pi_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eegmodel',
            name='model_type',
        ),
        migrations.RemoveField(
            model_name='trainingjob',
            name='model_type',
        ),
    ]
