# Generated by Django 4.2.20 on 2025-03-17 13:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pi_main', '0003_alter_prediction_actual_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_path', models.CharField(max_length=255)),
                ('accuracy', models.FloatField(default=0.0)),
                ('eval_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='pi_main.eegmodel')),
            ],
        ),
    ]
