# Generated by Django 5.2.1 on 2025-06-22 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.FileField(upload_to='datasets/')),
                ('participant_name', models.CharField(blank=True, max_length=100)),
                ('total_samples', models.IntegerField(default=0)),
                ('total_duration', models.FloatField(default=0.0, help_text='Duration in seconds')),
                ('sampling_rate', models.IntegerField(default=128)),
                ('n_channels', models.IntegerField(default=14)),
                ('word_counts', models.JSONField(default=dict, help_text='Count of samples per word')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WordClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('brain_region', models.CharField(max_length=100)),
                ('key_channels', models.JSONField(default=list)),
                ('instructions', models.TextField()),
                ('optimal_duration', models.FloatField(default=4.0, help_text='Optimal imagery duration in seconds')),
                ('difficulty_level', models.IntegerField(default=1, help_text='1=Easy, 5=Difficult')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('model_type', models.CharField(choices=[('cnn_lstm', 'CNN-LSTM Hybrid'), ('eegnet', 'EEGNet'), ('cnn_only', 'CNN Only'), ('lstm_only', 'LSTM Only')], default='cnn_lstm', max_length=20)),
                ('model_file', models.FileField(upload_to='models/')),
                ('scaler_file', models.FileField(upload_to='models/')),
                ('label_encoder_file', models.FileField(upload_to='models/')),
                ('window_size', models.IntegerField(default=512, help_text='Window size in samples')),
                ('n_classes', models.IntegerField(default=5)),
                ('n_channels', models.IntegerField(default=14)),
                ('accuracy', models.FloatField(default=0.0)),
                ('val_accuracy', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('epochs_trained', models.IntegerField(default=0)),
                ('training_time', models.FloatField(default=0.0, help_text='Training time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False, help_text='Use this model for predictions')),
                ('datasets_used', models.ManyToManyField(blank=True, to='eeg_classifier.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confusion_matrix', models.JSONField(default=dict)),
                ('per_class_precision', models.JSONField(default=dict)),
                ('per_class_recall', models.JSONField(default=dict)),
                ('per_class_f1', models.JSONField(default=dict)),
                ('training_loss', models.JSONField(default=list)),
                ('training_accuracy', models.JSONField(default=list)),
                ('validation_loss', models.JSONField(default=list)),
                ('validation_accuracy', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_classifier.classificationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('window_duration', models.FloatField(default=4.0, help_text='Duration in seconds for each prediction')),
                ('confidence_threshold', models.FloatField(default=0.5)),
                ('predictions', models.JSONField(default=list, help_text='List of predictions with timestamps')),
                ('accuracy_metrics', models.JSONField(default=dict, help_text='Accuracy analysis if ground truth available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_classifier.dataset')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_classifier.classificationmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('cnn_lstm', 'CNN-LSTM Hybrid'), ('eegnet', 'EEGNet'), ('cnn_only', 'CNN Only'), ('lstm_only', 'LSTM Only')], max_length=20)),
                ('window_size', models.IntegerField(default=512)),
                ('overlap', models.FloatField(default=0.5)),
                ('epochs', models.IntegerField(default=100)),
                ('batch_size', models.IntegerField(default=32)),
                ('learning_rate', models.FloatField(default=0.001)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preprocessing', 'Preprocessing'), ('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage')),
                ('current_epoch', models.IntegerField(default=0)),
                ('training_log', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('datasets', models.ManyToManyField(to='eeg_classifier.dataset')),
                ('final_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eeg_classifier.classificationmodel')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
