# Generated by Django 5.2.1 on 2025-07-03 00:32

import bci.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('prediction_interval', models.FloatField(default=8.0)),
                ('window_duration', models.FloatField(default=2.0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='stopped', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicted_class', models.IntegerField()),
                ('predicted_label', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('probabilities', models.JSONField()),
                ('prediction_time_ms', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='bci.predictionsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('session_file', models.FileField(upload_to=bci.models.session_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('approach', models.CharField(choices=[('motor_imagery', 'Motor Imagery'), ('future_approach', 'Future Approach')], default='motor_imagery', max_length=50)),
                ('channels', models.JSONField(default=list)),
                ('sampling_rate', models.IntegerField(default=128)),
                ('classes', models.JSONField(default=list)),
                ('total_samples', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eeg_device', models.CharField(choices=[('epoc_plus', 'EPOC+'), ('future_device', 'Future Device')], default='epoc_plus', max_length=50)),
                ('default_prediction_interval', models.FloatField(default=8.0)),
                ('default_window_duration', models.FloatField(default=2.0)),
                ('show_confidence_threshold', models.FloatField(default=0.5)),
                ('max_prediction_history', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('approach', models.CharField(choices=[('motor_imagery', 'Motor Imagery'), ('future_approach', 'Future Approach')], max_length=50)),
                ('model_file', models.FileField(upload_to=bci.models.model_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pt', 'pth', 'pkl'])])),
                ('scaler_file', models.FileField(blank=True, null=True, upload_to=bci.models.model_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pkl'])])),
                ('n_classes', models.IntegerField()),
                ('class_labels', models.JSONField()),
                ('channels', models.JSONField()),
                ('sampling_rate', models.IntegerField(default=128)),
                ('window_duration', models.FloatField(default=2.0)),
                ('validation_accuracy', models.FloatField(blank=True, null=True)),
                ('cross_val_mean', models.FloatField(blank=True, null=True)),
                ('cross_val_std', models.FloatField(blank=True, null=True)),
                ('training_epochs', models.IntegerField(blank=True, null=True)),
                ('model_config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed')], default='training', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('training_sessions', models.ManyToManyField(blank=True, to='bci.sessiondata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='predictionsession',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bci.trainedmodel'),
        ),
    ]
